//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarnizonEntities : DbContext
    {
        private static GarnizonEntities _context;
        public GarnizonEntities()
            : base("name=GarnizonEntities")
        {
        }
        
        public static GarnizonEntities GetContext()
        {
            if(_context == null)
            {
                _context = new GarnizonEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cпортсмен> Cпортсмен { get; set; }
        public virtual DbSet<Cпортсмен_Тренировка> Cпортсмен_Тренировка { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Команда> Команда { get; set; }
        public virtual DbSet<Окончанная_тренировка> Окончанная_тренировка { get; set; }
        public virtual DbSet<Отчёт_о_тренировке> Отчёт_о_тренировке { get; set; }
        public virtual DbSet<Результат_тренировки> Результат_тренировки { get; set; }
        public virtual DbSet<Таблица_результатов> Таблица_результатов { get; set; }
        public virtual DbSet<Тагер> Тагер { get; set; }
        public virtual DbSet<Тренировка> Тренировка { get; set; }
    }
}
