//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cпортсмен_Тренировка
    {
        public int Код_записи { get; set; }
        public Nullable<int> Код_спортсмена { get; set; }
        public Nullable<int> Код_тренировки { get; set; }
        public Nullable<int> Код_тагера { get; set; }
        public Nullable<int> Код_команды { get; set; }
    
        public virtual Cпортсмен Cпортсмен { get; set; }
        public virtual Команда Команда { get; set; }
        public virtual Тагер Тагер { get; set; }
        public virtual Тренировка Тренировка { get; set; }
    }
}
