//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Окончанная_тренировка
    {
        public int Код_окончанной_тренировки { get; set; }
        public Nullable<int> Код_тренировки { get; set; }
        public Nullable<int> Код_спортсмена { get; set; }
        public Nullable<System.TimeSpan> Время_окончания { get; set; }
        public string Причина { get; set; }
    
        public virtual Cпортсмен Cпортсмен { get; set; }
        public virtual Тренировка Тренировка { get; set; }
    }
}
