//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результат_тренировки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Результат_тренировки()
        {
            this.Отчёт_о_тренировке = new HashSet<Отчёт_о_тренировке>();
        }
    
        public int Код_результата_тренировки { get; set; }
        public Nullable<int> Код_тренировки { get; set; }
        public Nullable<int> Код_спортсмена { get; set; }
        public Nullable<int> Количество_попаданий { get; set; }
        public Nullable<int> Количество_захваченных_точек { get; set; }
        public Nullable<int> Количество_устранений { get; set; }
        public Nullable<bool> Перенесено { get; set; }
    
        public virtual Cпортсмен Cпортсмен { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчёт_о_тренировке> Отчёт_о_тренировке { get; set; }
        public virtual Тренировка Тренировка { get; set; }
    }
}
